/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seed-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Profile */
        post: operations["seed_profile_seed_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Stream */
        post: operations["recommend_stream_recommend_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve-spotify-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Spotify Url */
        post: operations["resolve_spotify_url_resolve_spotify_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Summed Similarity */
            summed_similarity: number;
            /** Tag Overlap */
            tag_overlap: number;
            /** Novelty Bonus */
            novelty_bonus: number;
            /** Final Score */
            final_score: number;
            /** Contributing Seeds */
            contributing_seeds: string[];
            /** Matched Tags */
            matched_tags: string[];
            /**
             * Explanation
             * @default []
             */
            explanation: string[];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RecommendRequest */
        RecommendRequest: {
            /** Seeds */
            seeds: components["schemas"]["Track"][];
            params: components["schemas"]["RecommendationParams"];
        };
        /** RecommendationParams */
        RecommendationParams: {
            /** Novelty */
            novelty: number;
            /** Genre Lock */
            genre_lock?: string[];
            /** Artist Diversity */
            artist_diversity: number;
            /**
             * Length
             * @default 10
             */
            length: number;
        };
        /** RecommendationResult */
        RecommendationResult: {
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Dropped Seeds */
            dropped_seeds: string[];
            params: components["schemas"]["RecommendationParams"];
            /**
             * Pool Exhausted
             * @default false
             */
            pool_exhausted: boolean;
        };
        /** ResolveSpotifyRequest */
        ResolveSpotifyRequest: {
            /** Url */
            url: string;
        };
        /** SeedErrorBody */
        SeedErrorBody: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
            /** Dropped Seeds */
            dropped_seeds: string[];
        };
        /** SeedProfile */
        SeedProfile: {
            /** Tags */
            tags: components["schemas"]["TagCount"][];
            /** Dropped Seeds */
            dropped_seeds: string[];
            /** Total Seeds */
            total_seeds: number;
        };
        /** SeedProfileRequest */
        SeedProfileRequest: {
            /** Seeds */
            seeds: components["schemas"]["Track"][];
        };
        /** TagCount */
        TagCount: {
            /** Name */
            name: string;
            /** Seed Count */
            seed_count: number;
        };
        /** Track */
        Track: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
        };
        /** TrackHit */
        TrackHit: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Image */
            image?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    seed_profile_seed_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_recommend_post: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResult"];
                    "text/csv": string;
                };
            };
            /** @description No successful seeds or no recommendations survived ranking */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedErrorBody"];
                };
            };
            /** @description Last.fm unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    recommend_stream_recommend_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_spotify_url_resolve_spotify_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveSpotifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
